title: SelfbotV1
description: Documentation for the Chat Selfbot
footer_content: 'Site by <a href="https://bjarnos.dev/">Bjarnos</a>'

theme: just-the-docs
url: https://docs.bjarnos.dev/

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
